CAC:
  iou_bound_high: 0.95
  iou_bound_low: 0.25
  stride: 4
DATASET:
  BCV:
    num_classes: 6
    test_list: ../data/BCV/test.txt
    testing_data_num: 6
    train_list: ../data/BCV/train.txt
    training_data_num: 24
  FLARE:
    num_classes: 14
    test_list: ../data/FLARE22/Flare22_test.txt
    testing_data_num: 10
    train_list: ../data/FLARE22/Flare22_train.txt
    training_data_num: 2040
  MMWHS:
    num_classes: 8
    test_list: ../data/MMWHS/MMWHS_test.txt
    testing_data_num: 6
    train_list: ../data/MMWHS/MMWHS_train.txt
    training_data_num: 14
  batch_size: 2
  labeled_bs: 1
  labeled_num: 40
  name: FLARE
  patch_size:
  - 96
  - 160
  - 160
backbone: unet_3D
base_lr: 0.01
began_condition_iter: 10000
began_eval_iter: 0
began_semi_iter: 6000
consistency: 0.1
consistency_rampup: 200.0
consistency_type: mse
continue_training: false
current_iter_num: 0
deterministic: 1
ema_decay: 0.99
exp: C3PS
gpu: 3,4
max_iterations: 30000
method: C3PS
model1_checkpoint: ../model/C3PS_2_MMWHS_condition/unet_3D/model1_iter_29600_dice_0.7324
model2_checkpoint: ../model/C3PS_2_MMWHS_condition/unet_3D/model2_iter_28600_dice_0.7509.pth
root_path: ../data/BraTS2019
seed: 1337
use_CAC: true
