CAC:
  iou_bound_high: 0.95
  iou_bound_low: 0.25
  stride: 4
DATASET:
  BCV:
    num_classes: 6
    test_list: ../data/BCV/test.txt
    testing_data_num: 6
    train_list: ../data/BCV/train.txt
    training_data_num: 24
  MMWHS:
    num_classes: 8
    test_list: ../data/MMWHS/MMWHS_test.txt
    testing_data_num: 6
    train_list: ../data/MMWHS/MMWHS_train.txt
    training_data_num: 14
  batch_size: 2
  labeled_bs: 1
  labeled_num: 4
  name: MMWHS
  patch_size:
  - 96
  - 160
  - 160
backbone: unet_3D
base_lr: 0.01
began_condition_iter: 8000
began_eval_iter: 1000
began_semi_iter: 4000
consistency: 0.1
consistency_rampup: 200.0
consistency_type: mse
continue_training: false
current_iter_num: 11400
deterministic: 1
ema_decay: 0.99
exp: test
gpu: 6,8
max_iterations: 30000
method: MT
model1_checkpoint: ../model/WWHS_10_BCV_condition/unet_3D/model1_iter_11400_dice_0.8602.pth
model2_checkpoint: ../model/WWHS_10_BCV_condition/unet_3D/model2_iter_22000_dice_0.8353.pth
root_path: ../data/BraTS2019
seed: 1337
use_CAC: false
