DATASET:
  BCV:
    cut_lower: -68
    cut_upper: 200
    num_classes: 6
    test_list: ../data/BCV/test.txt
    testing_data_num: 6
    train_list: ../data/BCV/train.txt
    training_data_num: 24
  FLARE:
    num_classes: 14
    test_list: ../data/FLARE22/Flare22_test.txt
    testing_data_num: 10
    train_list: ../data/FLARE22/Flare22_train.txt
    training_data_num: 2038
  MMWHS:
    cut_lower: -1000
    cut_upper: 1000
    num_classes: 8
    test_list: ../data/MMWHS/MMWHS_test.txt
    testing_data_num: 6
    train_list: ../data/MMWHS/MMWHS_train.txt
    training_data_num: 14
  affine_trans: false
  batch_size: 2
  cutout: true
  edge_prob: 0.1
  labeled_bs: 1
  labeled_num: 2
  patch_size:
  - 96
  - 160
  - 160
METHOD:
  Baseline: null
  C3PS:
    iou_bound_high: 0.95
    iou_bound_low: 0.25
    stride: 4
  CPS: null
  DAN: null
  EM: null
  ICT:
    ict_alpha: 0.2
  MT: null
  UAMT: null
backbone: unet_3D
began_condition_iter: 6000
began_eval_iter: 300
began_semi_iter: 4000
consistency: 0.1
consistency_rampup: 200.0
consistency_type: mse
continue_training: false
current_iter_num: 2000
dataset_name: MMWHS
deterministic: 1
ema_decay: 0.99
exp: cut_sgd_test_oldcode
gpu: '1'
initial_lr: 0.01
lr_scheduler_eps: 0.001
lr_scheduler_patience: 30
max_iterations: 20000
method: C3PS
model:
  f_maps: 16
  final_sigmoid: false
  in_channels: 1
  is_segmentation: true
  layer_order: gcr
  name: Semi3DUNet
  num_groups: 8
  num_levels: 5
  out_channels: 8
model2_checkpoint: ../model/BCV_4_C3PS_test3_cut_affine_adam/unet_3D/model2_iter_15400_dice_0.5562.pth
model_checkpoint: ../model/BCV_4_C3PS_test3_cut_affine_adam/unet_3D/model1_iter_9600_dice_0.664.pth
optimizer_type: Adam
root_path: ../data/dBraTS2019
save_checkpoint_freq: 3000
seed: 1337
show_img_freq: 100
use_CAC: true
val_freq: 200
weight_decay: 1.0e-05
